CB vom 10.02.2022
importPI19fromDHGE/dhge-pi19-sem6 pull request #13
Opened 2022-02-10 10:44 UTC by ZeroPointMax

2022-02-10 18:24 UTC, RvNovae commented on CB-KUSCHE/README.md
> +- Lexer nimmt Zeichenstrom, assoziiert diese mit Tokens, gibt Tokenstrom aus
```suggestion
- Lexer nimmt Zeichenstrom, assoziiert diesen mit Tokens, gibt Tokenstrom aus
```

2022-02-10 18:24 UTC, RvNovae commented on CB-KUSCHE/README.md
> +    - solange shiften, bis reduziert werden kann: poppt alles vom Stack und reduzierte Funktion auf den Stack gelegt
```suggestion
    - solange shiften, bis reduziert werden kann: poppt alles vom Stack und reduzierte wird Funktion auf den Stack gelegt
```

2022-02-10 18:24 UTC, RvNovae commented on CB-KUSCHE/README.md
> +- runde Klammern für Gruppierungen
Vielleicht sollte man erwähnen, dass das einfach nur die EBNF Darstellung ist?

2022-02-10 20:12 UTC, ZeroPointMax commented on CB-KUSCHE/README.md
> +    - solange shiften, bis reduziert werden kann: poppt alles vom Stack und reduzierte Funktion auf den Stack gelegt
Nicht eher so hier:

```suggestion
    - solange shiften, bis reduziert werden kann: poppt alles vom Stack und reduzierte Funktion wird auf den Stack gelegt
```

2022-02-11 08:19 UTC, ZeroPointMax commented on CB-KUSCHE/README.md
> +- runde Klammern für Gruppierungen
```suggestion
- Darstellung mithilfe EBNF
  - Oder-Strich für Alternativen
  - eckige Klammern für optionale Ausdrücke
  - geschweifte Klammern für 0 oder mehr Mal
  - runde Klammern für Gruppierungen
```

2022-02-11 08:20 UTC, ZeroPointMax commented on CB-KUSCHE/README.md
> +- runde Klammern für Gruppierungen
siehe unten

2022-02-11 08:33 UTC, RvNovae approved these changes

2022-02-11 08:33 UTC, RvNovae commented on CB-KUSCHE/README.md
> +  - Achtung: eigentlich ist der falsch; die Regel kann nicht zwischen Float und Int unterscheiden $\rightarrow$ Zweideutigkeit
Vielleicht das Bild noch hinzufügen.
Da nicht prüfungsrelevant, wärs mir aber im Grunde auch egal 😅

2022-02-11 09:50 UTC, Steve2955 requested changes

2022-02-11 10:40 UTC, ZeroPointMax commented on CB-KUSCHE/README.md
> +  - Achtung: eigentlich ist der falsch; die Regel kann nicht zwischen Float und Int unterscheiden $\rightarrow$ Zweideutigkeit
Ahja, Danke, das habe ich wieder vergessen 😅

2022-02-11 13:22 UTC, Steve2955 approved these changes

2022-02-11 13:22 UTC, merged

2022-02-12 20:38 UTC, ZeroPointMax commented
@Steve2955 Jaja, jetzt hast du zu zeitig gemergt 😅