IT-Recht 14.02.22
importPI19fromDHGE/dhge-pi19-sem6 pull request #17
Opened 2022-02-14 17:18 UTC by RvNovae

2022-02-14 17:21 UTC, ZeroPointMax commented
> Nach dem ersten oder zweiten Kolleg hab ich dann irgendwann abgeschaltet ...
> 
> Enthält Korrekturen von @ZeroPointMax :D

Ja ich hab auch alles von mir ergänzt, aber mir gehts da mit der Aufmerksamkeit ähnlich.

2022-02-14 17:22 UTC, ZeroPointMax commented
Habe mich mal formell aus dem Review genommen, ich bin ja biased :^)

2022-02-15 11:01 UTC, Steve2955 requested changes
siehe #19

2022-02-16 06:51 UTC, Steve2955 approved these changes

2022-02-16 07:11 UTC, ZeroPointMax approved these changes
LGTM

2022-02-16 07:11 UTC, merged