Make ToC-Action run on every .md except top-level
importPI19fromDHGE/dhge-pi19-sem6 pull request #30
Opened 2022-02-22 12:10 UTC by nukerxy

2022-02-22 12:27 UTC, ZeroPointMax approved these changes
Kann nicht schaden oder?

2022-02-22 12:28 UTC, Steve2955 requested changes

2022-02-22 12:28 UTC, Steve2955 commented on .github/workflows/toc.yml
> +        TARGET_PATHS: "./[A-Z]*[A-Z]-[A-Z]*[A-Z]/*.md"
```suggestion
        TARGET_PATHS: "./[A-Z]*[A-Z]-[A-Z]*[A-Z]/**.md"
```
@nukerxy @ZeroPointMax Oder so? Gibt es einen konkreten Fall wie wir das brauchen?

2022-02-22 12:40 UTC, ZeroPointMax commented on .github/workflows/toc.yml
> +        TARGET_PATHS: "./[A-Z]*[A-Z]-[A-Z]*[A-Z]/*.md"
ähm das matcht dann rekursiv oder?

2022-02-22 13:28 UTC, Steve2955 commented on .github/workflows/toc.yml
> +        TARGET_PATHS: "./[A-Z]*[A-Z]-[A-Z]*[A-Z]/*.md"
> ähm das matcht dann rekursiv oder?

Ja genau, anders werden die files im `extra`-Ordner mMn nicht gematched.

2022-02-22 13:42 UTC, Steve2955 commented on .github/workflows/toc.yml
> +        TARGET_PATHS: "./[A-Z]*[A-Z]-[A-Z]*[A-Z]/*.md"
```suggestion
        TARGET_PATHS: "./[A-Z]*[A-Z]-[A-Z]*[A-Z]/README.md,./[A-Z]*[A-Z]-[A-Z]*[A-Z]/extra/*.md"
```

So würde mir das aber am besten gefallen^^

2022-02-22 20:13 UTC, nukerxy commented on .github/workflows/toc.yml
> +        TARGET_PATHS: "./[A-Z]*[A-Z]-[A-Z]*[A-Z]/*.md"
> > ähm das matcht dann rekursiv oder?
> 
> Ja genau, anders werden die files im `extra`-Ordner mMn nicht gematched.
> 

stehe auf dem Schlauch - wieso ausgerechnet extra, was ist mit appendix, assets; was ist der Unterschied?

2022-02-23 09:47 UTC, Steve2955 commented on .github/workflows/toc.yml
> +        TARGET_PATHS: "./[A-Z]*[A-Z]-[A-Z]*[A-Z]/*.md"
```suggestion
        TARGET_PATHS: "./[A-Z]*[A-Z]-[A-Z]*[A-Z]/README.md,./[A-Z]*[A-Z]-[A-Z]*[A-Z]/appendix/*.md"
```
@nukerxy Tut mir Leid, ich habe das hier selbst etwas durcheinandergehauen. 

Der TOC macht mMn nur für den `appendix` Sinn. Hier nochmal die Erläuterung der Ordnerstruktur:

```text
<Modul>/
├── appendix/           <- Anhang: Praktika, Glossar, ...
│   ├── <Praktika>.md
│   ├── <Cheatsheet>.md
│   └── <Glossar>.md
├── extra/              <- Zusätzliches: Vorträge, Programmierübungen ...
│   ├── <Vortag>.pdf
│   └── excercise-01/
│       └── main.c
├── assets/             <- Bilder
│   ├── <filename>.png
│   ├── <filename>.png
│   └── <filename>.svg
└── README.md           <- Modulmitschriften
```

2022-02-23 09:51 UTC, Steve2955 approved these changes

2022-02-23 14:41 UTC, merged