Forensik 22. und 23.02.2022
importPI19fromDHGE/dhge-pi19-sem6 pull request #31
Opened 2022-02-24 07:47 UTC by RvNovae

Ist absolut unvollständig, weil mich das zu Tode gelangweilt hat.
Ergänzungen gerne gesehen!

2022-02-24 08:15 UTC, ZeroPointMax commented
Oh man ich muss es auch noch sichten, mal sehen, ob ich was beitragen kann ._.

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +  - Im Vordergrund steht dier zeitnahe Wiederverwendung der betroffenen Systeme
```suggestion
  - Im Vordergrund steht die zeitnahe Wiederverwendung der betroffenen Systeme
```

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +  - **Nachteil**: Heterogene Systemlandschaften erfordern ein hohes Maß an Analyse und Know-How $\rightarrow$ Zeitaufwendig
```suggestion
  - **Nachteil**: Heterogene Systemlandschaften erfordern ein hohes Maß an Analyse und Know-How $\rightarrow$ zeitaufwendig
```

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +- Weitere Organisatorische Maßnahmen
```suggestion
- Weitere organisatorische Maßnahmen
```

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +# ???
???

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +  - erfolgt Betriebssystemabhängig
```suggestion
  - erfolgt abhängig von Betriebssystem
```

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +  - erfolgt Betriebssystem unabhängig
```suggestion
  - erfolgt betriebssystem**un**abhängig
```

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +  - UrhG-Erkennen urheberrechtlich geschützter Werke durch Hash-Abgleich (MD4-Emule)
```suggestion
  - UrhG: Erkennen urheberrechtlich geschützter Werke durch Hash-Abgleich (MD4-Emule)
```

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +- Ersteinschreiter für digitale Beweismittel (Digital Evidence First Responder - DEFR)
Das habe ich total verpeilt, und mich dann gewundert, was ein DEFR ist 😵‍💫

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +## Grundlegende Aspekte bei der Bearbeitung von digitalen Beweismitteln
```suggestion

## Grundsätze in der digitale Forensik

- Relevanz
- Vollständigkeit
- Verlässlichkeit
- Rechtmäßigkeit

## Grundlegende Aspekte bei der Bearbeitung von digitalen Beweismitteln
```

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +## Obhutskette
Kommentar auf Papier: 

> bla bla

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +- Sichern und Kontrollieren des Bereis, in dem sich die Geräte befinden
```suggestion
- Sichern und Kontrollieren des Bereichs, in dem sich die Geräte befinden
```

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +    - handschriftliche Aufzeichnungen sind hinterher schwerer zu verändert oder zu fälschen
```suggestion
    - handschriftliche Aufzeichnungen sind hinterher schwerer zu verändern oder zu fälschen
```

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +- Security Identifier
Kann es auf einem System also immer nur <500 Admins geben?

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +
```suggestion

### Linux-Dateisysteme 

- FAT 12/16/32
- ext 1/2/3/4
- CDFS
- ReiserFS
- UFS

<!-- 
TODO

schreibgeschützt mounten
Rollensystem ugr, rwx, chmod

nützliche Befehle Live
- rpm-qu
- dpkg -l
- apt-list (?)
- where is
- which
- echo $PATH

PostMortem
- /opt/..
- .. ToDo Folie 3/52


- history
- grep auth-log nach sudo-Befehlen
- Zeitzone, DNS, Betriebssysteminfo ...
- Prozesse, Netzwrkverbindungen, Logdateien
- Rootkit Scanner
- syst internal suite (?????????????????????)
- ....
-->
```

2022-02-28 19:48 UTC, nukerxy commented on PRO-STRASS/README.md
> +## Hacking
- Root-Kit
- TCP-View
- PDF Malware Analysis
- Wireshark

2022-02-28 19:49 UTC, nukerxy commented
Vielen Dank für diese doch sehr umfassenden Mitschriften

2022-03-02 10:26 UTC, RvNovae commented on PRO-STRASS/README.md
> +# ???
Ich glaub da hatte seine Bildschirmübertragung gesponnen und deswegen hab ich 5 Folien nicht mitbekommen.
Weil ich er dachte er wäre immer noch bei der Zusammenfassung...

2022-03-06 11:53 UTC, nukerxy approved these changes
Ab # Bekämpfung der Computerkriminalität ist ein Foliensatz, den wir noch nicht haben?

2022-03-06 18:18 UTC, ZeroPointMax commented on PRO-STRASS/README.md
> +- syst internal suite (?????????????????????)
[SysInternals - dein Lebensretter als Admin](https://docs.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite)

2022-03-06 18:56 UTC, ZeroPointMax commented on PRO-STRASS/README.md
> +- Unterstützte Architekturen: X86 (32 Bit), X64/iA64 (64 Bit)
Fehlt hier nicht ARM64?

2022-03-06 19:07 UTC, ZeroPointMax requested changes
Ich überarbeite gerade

2022-03-06 19:45 UTC, ZeroPointMax approved these changes
@RvNovae vielen Dank für die doch guten Mitschriften.
Der Form halber adde ich mal @nukerxy, damit er folgendes auch sieht:

Ich habe mir nochmal erlaubt, chmod und die Rechtematrix darzustellen, weil die auf dem Todo standen. Hoffe das ist OK?

2022-03-06 19:51 UTC, ZeroPointMax commented on PRO-STRASS/README.md
> +    - System angeschaltet
https://www.duden.de/konjugation/ausschalten

2022-03-06 19:52 UTC, ZeroPointMax commented on PRO-STRASS/README.md
> +    - System angeschaltet
ausgeschalten klingt trotzdem besser, aber hey :D

2022-03-08 16:33 UTC, Steve2955 commented on PRO-STRASS/README.md
> +- Die Benutzerspezifischen liegen in `C:\Users\User\`
Entweder beides mit trailing Slash oder beides ohne 🤔 

```suggestion
- Die Datenbanken liegen in Dateiform in `C:\Windows\System32\Config\`
- Die Benutzerspezifischen liegen in `C:\Users\User\`
```

```suggestion
- Die Datenbanken liegen in Dateiform in `C:\Windows\System32\Config`
- Die Benutzerspezifischen liegen in `C:\Users\User`
```

2022-03-08 16:34 UTC, Steve2955 approved these changes

2022-03-08 17:45 UTC, ZeroPointMax approved these changes

2022-03-08 17:50 UTC, merged