NET vom 02.03.2022
importPI19fromDHGE/dhge-pi19-sem6 pull request #32
Opened 2022-03-02 14:15 UTC by ZeroPointMax

An manchen Stellen sind noch TODOs, für die die Folien nötig sind

2022-03-07 07:31 UTC, Steve2955 reviewed
Nur ein paar Kommentare. Ich würde noch etwas warten, bis die Folien von ihm da sind.

2022-03-07 07:31 UTC, Steve2955 commented on NET-FELDMANN/README.md
> +- Cheatsheet 1x DIN A4 beidseitig
```suggestion
- schriftliche Klausur (60 min)
- wird zu 50% verrechnet (Rest `NET-BARIE` aus Semester 5)
- eine DIN-A4-Seite beidseitig beschriftet als Cheatsheet erlaubt
```

2022-03-07 07:31 UTC, Steve2955 commented on NET-FELDMANN/README.md
> +  - gemeinsames Ziel
```suggestion
Ein verteiltes System ist ein System bestehend aus...

- mehreren Einzelkomponenten
- auf unterschiedlichen Rechnern
- kein gemeinsamen Speicher
- Kooperation mittels Nachrichtenaustausch (Netzwerk)
- gemeinsames Ziel
```

2022-03-07 07:31 UTC, Steve2955 commented on NET-FELDMANN/README.md
```suggestion

<!--Keywords aus dem Chat
- ACID
- REST
- Erlang
- JBOSS
- J2EE
- https://gitlab.com/rak-n-rok/krake
- Lambda-Kalkül
- secustack.com
- heroku.com
- OpenShift
-->
```

Wollen wir die Keywords vielleicht mit dokumentieren? Sind eigentlich ein paar interessante Sachen dabei. Gerne auch Vorschläge für andere Stellen im Dokument.

2022-03-07 07:31 UTC, Steve2955 commented on NET-FELDMANN/README.md
> +- mehrstufige Architekturen: "divide et impera"
```suggestion
- mehrstufige Architekturen: *"divide et impera"*
```

2022-03-07 07:31 UTC, Steve2955 commented on NET-FELDMANN/README.md
> +
```suggestion

<!-- gerne als Klausurfrage (IaaS,PaaS,SaaS)-->

```

2022-03-07 11:28 UTC, RvNovae reviewed
Vielen Dank für die tollen Mitschriften!

Ich hatte mir noch notiert, dass das Cap Theorem höchst prüfungsrelevant sein soll.

2022-03-07 11:28 UTC, RvNovae commented on NET-FELDMANN/README.md
> +<!--NET hier, aber haben Sie schon mal eine Firma gegründet?-->
😆

2022-03-07 11:28 UTC, RvNovae commented on NET-FELDMANN/README.md
OpenStack würd ich direkt noch beisteuern

2022-03-07 11:30 UTC, RvNovae commented on NET-FELDMANN/README.md
OpenStack würd ich direkt noch beisteuern.

2022-03-07 15:14 UTC, ZeroPointMax commented on NET-FELDMANN/README.md
> +- Cheatsheet 1x DIN A4 beidseitig
🤪

2022-03-07 19:27 UTC, RvNovae approved these changes

2022-03-30 13:10 UTC, ZeroPointMax commented
> @ZeroPointMax [Bin auch etwas am Mitschreiben](https://github.com/importPI19fromDHGE/dhge-pi19-sem6/tree/ybe-net)

Ahjo cool, können wir nacher mal vergleichen

2022-04-01 14:23 UTC, nukerxy commented on NET-FELDMANN/README.md
> +<!--Anm. Max: er hat sehr auf Caching vs. Repl hingewiesen - klausurrelevant?-->
ja, denke schon!

2022-04-01 14:23 UTC, nukerxy commented on NET-FELDMANN/README.md
> +Siehe DBS.
aus ybe-net
```suggestion

> auf Konsistenz ausgelegt
- **Atomicity:** Entweder vollständige oder keine Ausführung
- **Consistency:** nur Übergänge von konsistentem Zustand zu konsistentem Zustand
- **Isolation:** Keine Überlappung von Transaktionen, die sich gegenseitig beeinflussen können
- **Durability:** Nach Abschluss einer Transaktion werden Daten garantiert dauerhaft in einer Datenbank gespeichert

#### BASE

> auf Verfügbarkeit ausgelegt $\rightarrow$ einfach skalierbar (best efford, optimistic)
- **Basically Available:** Lese- und Schreiboperationen sind immer verfügbar
  - `write` bei Konflikten nicht unbedingt persistent
  - `read` liefert nicht unbedingt zuletzt gespeicherte (bzw. konsistente) Daten
- **Soft state:** keine Garantie für Konsistenz (nur Wahrscheinlichkeit)
- **Eventual consistency:** nach ausreichender Zeit kann von einem konsistenten Zustand ausgegangen werden

```

2022-04-01 14:23 UTC, nukerxy commented on NET-FELDMANN/README.md
> +## Zwei-Phase-Commits
```suggestion
## Zwei-Phasen-Commit-Protokoll
```

2022-04-01 14:23 UTC, nukerxy commented on NET-FELDMANN/README.md
> +  - **Commit-Entscheidungen werden nie rückgängig gemacht**
vgl. ybe-net
```suggestion
**Phase 2:**

- **Versenden eines "Commits"** durch Koordinator $\rightarrow$ alle temporären Daten müssen persistent gemacht werden
  - Bedingung: Phase 1 erfolgreich
  - Koordinator versendet Commit-Befehl
  - alle Teilnehmer müssen Daten persistent speichern
- **Bestätigung persistenter Speicherung** gegenüber Koordinator
  - Teilnehmer bestätigen Erfolg

- Problem: wenn Commit-Entscheidung stattgefunden hat, aber ein Teilnehmer nicht bestätigt (z.B. Absturz)
  - betroffener Teilnehmer muss konsistenten Zustand anfordern und *nachholen* (nicht verwechseln mit Roll-forward) <!--Prüfungsrelevant!-->
  - **Commit-Entscheidungen werden nie rückgängig gemacht**
```

2022-04-01 14:23 UTC, nukerxy commented on NET-FELDMANN/README.md
> +
aus ybe-net
```suggestion
- MariaDB (auf Konsistenz optimiert)
- MongoDB (auf Verfügbarkeit optimiert)
- Gaia-X - https://gaia-x.eu/news/events/gaia-x-hackathon-3
- Content Distribution Networks
- Paxos (-Protokoll)
- Consensus-Protokolle
- Edge-Cloud
```

2022-04-01 16:44 UTC, nukerxy requested changes
siehe suggestions

2022-04-01 21:38 UTC, ZeroPointMax commented on NET-FELDMANN/README.md
> +Siehe DBS.
Ah hier werde ich manuell mergen müssen

2022-04-01 21:38 UTC, ZeroPointMax commented
@nukerxy vielen Dank für die Mitarbeit ^^

2022-04-04 07:06 UTC, ZeroPointMax commented
Die TODOS werden bis auf Screenshot 1, hier. NS und +/- bei Optimierung in der neuen Branch von heute gelöst

2022-04-04 19:47 UTC, nukerxy approved these changes

2022-04-05 14:39 UTC, merged