Computer Forensik 09.02.22
importPI19fromDHGE/dhge-pi19-sem6 pull request #8
Opened 2022-02-09 17:26 UTC by RvNovae

Mit der Bitte um Ergänzungen

2022-02-09 19:10 UTC, ZeroPointMax requested changes
puh

2022-02-09 19:10 UTC, ZeroPointMax commented on PRO-STRASS/README.md
> +
```suggestion
# Was ist digitale Forensik?

ist die streng methodisch vorgenommene Datenanalyse auf Datenträgern und Computernetzen zur Aufklärung von Vorfällen unter Einbeziehung der Möglichkeiten der strategischen Vorbereitung insbesondere aus der Sicht des Anlagenbetreibers eines IT-Systems [BSI-Leitfaden IT-Forensik, 2011]

## Worum geht es bei der Computer Forensik?

- Nachweis und Ermittlung von Straftaten aus dem Bereich der Computerkriminalität

## Ziele der forensischen Analyse

- Identifikation des Angreifers
- Erkennen der Methode
- Ermittlung der Schadens
- Sicherung der Beweise

## Arbeitsgebiete der digitalen Forensik

- Datenträger-, Multimedia-, Car-, Mobilfunk-, Cloud-, IoT-, Netzwerk-, Memory-Forensik
- Forensische Linguistik
- Überschneidungen zu anderen Gebieten der Informationssicherheit
  - Forensic Intelligence (Predictive Policing, Untersuchung von Radikalisierung im Internet)
  - Informationssicherheitsmanagement
  - Schadsoftware-Analyse / Reverse Engineering
  - Untersuchungen im Darknet
  - Kryptowährungen / Blockchain-Untersuchung

## Herausforderungen der digitalen Forensik

- Massendaten in der Datenträger-Forensik: Datenmengen immer größer, Speicherplatz immer günstiger
- Faktor Zeit: bis zur Entdeckung eines Vorfalls vergehen oft Monate

## Klassifizierung der Täter

```

2022-02-09 19:10 UTC, ZeroPointMax commented on PRO-STRASS/README.md
> +
fände ich so schöner strukturiert

2022-02-09 19:10 UTC, ZeroPointMax commented on PRO-STRASS/README.md
> +# Was beschreibt das Locard'sche Prinzip?
```suggestion
## Was sind digitale Spuren?

- basieren auf Daten, welche in Computersystemen gespeichert sind oder übertragen wurden
- werden erst durch ihre Interpretation von physischen Spuren über unterschiedliche Interpretationsebenen zu verwertbaren Spuren

## Was beschreibt das Locard'sche Prinzip?
```

2022-02-09 19:10 UTC, ZeroPointMax commented on PRO-STRASS/README.md
> +# S-A-P-Modell
Mir ist das [SCP Modell](https://scp-wiki.wikidot.com) sympathischer :^)

2022-02-09 19:10 UTC, ZeroPointMax commented on PRO-STRASS/README.md
> +
```suggestion
  - Sozial, technisch, politisch, finanziell, staatlich

## Herausforderungen in der IT-Forensik

- die Daten werden mehr, damit die benötigte Zeit (oft Monate)
- hohe Dunkelziffer an Angriffen

```

2022-02-09 19:10 UTC, ZeroPointMax commented on PRO-STRASS/README.md
> +- Sekundär: Vorsorge
```suggestion
- Primär: Aufklärung
  - Sicherstellung be- und entlastenden Beweisen
  - sichergestellte Daten müssen systematisch analysierbar und gerichtsverwertbar sein
  - Rekonstruktion der Ereignisse
- Sekundär: Vorsorge
  - KVP!!!
  - Abschreckung vor zukünftigen Straftaten
```

2022-02-09 19:10 UTC, ZeroPointMax commented on PRO-STRASS/README.md
> +
```suggestion
- Strategische Vorbereitung $\rightarrow$ Operative Vorbereitung $\rightarrow$ Datensammlung $\rightarrow$ Datenreduktion $\rightarrow$ Datenanalyse $\rightarrow$ Dokumentation

- Leitfaden: ISO 27037
- es gibt keine verpflichtenden Leitlinien oder gesetzliche Vorgaben
- Anforderungen an die Vorgehensweise bei neuen Methoden: Akzeptanz in der Fachwelt, Glaubwürdigkeit, Reproduzierbarkeit, Integrität: Spuren werden nicht verändert, Kausalität herstellbar, Dokumentation nachvollziehbar

```

2022-02-10 06:06 UTC, nukerxy commented on PRO-STRASS/README.md
> +
Das Bundesverfassungsgericht stellte fest, dass unter den Verarbeitungs- und Verknüpfungsmöglichkeiten der Informationstechnologie auch ein für sich gesehen belangloses Datum einen neuen Stellenwert bekommen kann und es insoweit keine belanglosen Daten gibt. [Quele](https://www.arag.de/service/infos-und-news/rechtstipps-und-gerichtsurteile/sonstige/08747/#:~:text=Das%20Bundesverfassungsgericht%20stellte%20fest%2C%20dass,insoweit%20keine%20belanglosen%20Daten%20gibt.)

2022-02-10 11:02 UTC, sthinbetween approved these changes

2022-02-11 07:14 UTC, nukerxy approved these changes

2022-02-11 08:15 UTC, ZeroPointMax approved these changes

2022-02-11 08:15 UTC, merged