IT-Recht 09.02.2022
importPI19fromDHGE/dhge-pi19-sem6 pull request #9
Opened 2022-02-09 17:35 UTC by RvNovae

Mitte der Bitte um Ergänzung

2022-02-09 17:42 UTC, ZeroPointMax requested changes
Werde wie abgesprochen meine Ergänzungen reincommitten

2022-02-09 18:46 UTC, ZeroPointMax commented
So hab ergänzt

2022-02-09 18:48 UTC, ZeroPointMax commented on ISR-MUELLER/README.md
> +- es gibt keine belanglosen Daten
War hier nicht eher gemeint, dass keine belanglosen Daten erfasst werden dürfen?

2022-02-10 06:38 UTC, nukerxy commented on ISR-MUELLER/README.md
> +- es gibt keine belanglosen Daten
siehe #8

2022-02-10 06:58 UTC, sthinbetween approved these changes

2022-02-10 07:06 UTC, ZeroPointMax approved these changes
![image](https://user-images.githubusercontent.com/26359277/153355362-c67491a1-7ca6-4468-bd15-3467fb7d8d2f.png)

2022-02-10 07:06 UTC, merged

2022-02-10 07:12 UTC, Steve2955 commented on ISR-MUELLER/README.md
> +- Personalrat hat Einfluss auf diese
```suggestion
- geregelt durch Gesetze oder Kollektivvereinbarung (Betriebs-/Dienstvereinbarungen)
- Betriebs-/Personalrat hat Einfluss auf diese
```

2022-02-10 07:12 UTC, Steve2955 commented on ISR-MUELLER/README.md
> +  - Personalrat kann mitwirken aber nicht entscheiden
```suggestion
- Fälle der vollen Mitbestimmung $\rightarrow$ Betriebs-/Personalrat **muss** zustimmen
- Fälle der Mitwirkung $\rightarrow$ Betriebs-/Personalrat kann mitwirken aber nicht entscheiden
```

2022-02-10 07:12 UTC, Steve2955 commented on ISR-MUELLER/README.md
> +- Straftaten verhindern
```suggestion
- Straftaten (z.B. Urheberrechtsverstöße) durch Mitarbeiter verhindern
```

2022-02-10 07:12 UTC, Steve2955 commented on ISR-MUELLER/README.md
> +- Straftaten verhindern
Weiß nicht, ob "Straftaten" das richtige Wort ist.

```suggestion
- Rechtsverletzungen (z.B. Urheberrechtsverstöße) durch Mitarbeiter verhindern
```

2022-02-10 07:12 UTC, Steve2955 commented on ISR-MUELLER/README.md
> +- bei illegalen Handlungen darf direkt gekündigt werden, ansonsten muss zunächst gemahnt werden
```suggestion
- bei illegalen Handlungen darf außerordentlich gekündigt werden, ansonsten kann abgemahnt werden
```
Das trifft es besser, oder?

2022-02-10 07:12 UTC, Steve2955 commented on ISR-MUELLER/README.md
> +- "Wer weiß wann und bei welcher Gelegenheit was über mich?" $\rightarrow$ Grundrecht
```suggestion
- *"Wer weiß wann und bei welcher Gelegenheit was über mich?"* $\rightarrow$ Grundrecht
```